name: My-First-Pipeline

on: [push]

jobs:
  check-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display success message
        run: echo "The pipeline is running successfully in project1!"
        
