name: Math-Project-Stats

on: [push]

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Project Summary
        run: |
          echo "--- Layihə Hesabatı ---"
          echo "Layihə adı: Project1"
          echo "-----------------------"
          
      - name: Count test files
        run: |
          echo "Bütün qovluqlardakı PDF testlərinin siyahısı:"
          find . -iname "*pdf" -type f
          echo "-----------------------"
          echo "Cəmi PDF sayı:"
          find . -iname "*pdf" -type f | wc -l
